import type { ArticleContent } from '../types'

export const modelingPhilosophy: ArticleContent = {
  title: 'Modeling Philosophy',
  description:
    'Why the platform models land the way it does. Intentional simplifications, how abstractions map to real-world constraints, and preventing farmers from feeling constrained by the system.',
  sections: [
    {
      heading: 'Why the System Models Land This Way',
      content: `Every software system makes modeling choices. The platform models grazing land with specific abstractions:

**Farm** → The top-level container. One farm per operation. Contains all paddocks, settings, and history.

**Paddock** → Discrete management unit. The smallest area you'd move animals to or from. Has boundaries, status, and observations.

**Section** → Daily grazing allocation. A portion of a paddock recommended for single-day use. Generated by the AI, not permanent.

**Zone** → Infrastructure or feature within a paddock. Water sources, shade areas, mineral stations. Affects recommendations but isn't a grazing unit.

These abstractions trade precision for usability. Real land has infinite complexity; the model captures enough to make useful decisions.`,
    },
    {
      heading: 'Intentional Simplifications',
      content: `The model deliberately ignores certain realities:

**Soil variability within paddocks**
Reality: Soil type, drainage, and fertility vary across a paddock.
Model: Treats each paddock as uniform.
Why: Satellite resolution doesn't capture fine-grained soil data. Paddock-level NDVI reflects the aggregate condition.

**Species composition**
Reality: Pastures contain multiple plant species with different grazing values.
Model: Doesn't distinguish species.
Why: Species detection requires ground-truthing. NDVI correlates with overall forage quality regardless of composition.

**Animal behavior preferences**
Reality: Animals prefer certain areas within paddocks.
Model: Assumes relatively uniform grazing pressure within sections.
Why: Section sizing and rotation speed limit selective grazing. The platform recommends; the farmer manages execution.

**Microtopography**
Reality: Hills, swales, and contours affect growing conditions.
Model: Flat representation of paddock boundaries.
Why: Topographic effects are captured in NDVI readings. Explicit terrain modeling adds complexity without proportional benefit.`,
    },
    {
      heading: 'How Abstractions Map to Reality',
      content: `Each abstraction serves specific functions:

**Paddock Boundaries → Satellite Pixels**
Paddock geometry defines which satellite pixels to aggregate. NDVI is calculated by averaging all pixels that fall within the boundary.

**Paddock Boundaries → Movement Constraints**
Boundaries represent where animals can physically go. Fences, roads, and natural barriers define these limits.

**Sections → Grazing Pressure Distribution**
Sections guide where to concentrate animals. By recommending ~20% of paddock area, the platform suggests how to distribute grazing pressure.

**Status Calculations → Decision Support**
Paddock status (ready/recovering/grazed) translates complex variables into actionable categories. Farmers don't need to interpret raw NDVI; status provides the answer.

**Zones → Constraint Inputs**
Water zones affect section recommendations. The AI considers water access when generating section geometry.`,
    },
    {
      heading: 'Preventing "Boxed In" Feeling',
      content: `A common concern with management software: does it constrain farmers to rigid rules?

The platform addresses this through:

**Defaults, Not Requirements**
Every threshold can be overridden. The default NDVI of 0.40 is a starting point. Your paddock might work at 0.35 or need 0.50.

**Recommendations, Not Commands**
Plans are pending until approved. You can always reject and do something different.

**Override Mechanisms**
Per-paddock threshold overrides accommodate known differences. Irrigated paddocks might have different standards than dryland.

**Feedback Loops**
When you override recommendations, the system records why. Consistent overrides signal that defaults need adjustment.

**Transparency**
The reasoning behind each recommendation is visible. You're not following a black box—you can evaluate the logic.

The goal: provide decision support without constraining decision-making. Experienced farmers know things the system doesn't. The platform should help, not dictate.`,
    },
    {
      heading: 'When the Model Breaks Down',
      content: `Every model has limits. The platform's abstractions work poorly when:

**Paddock heterogeneity is extreme**
If one half of a paddock is irrigated and the other isn't, treating them as one unit distorts recommendations. Solution: split into two paddocks.

**Infrastructure changes frequently**
Temporary fencing that changes weekly doesn't fit the stable paddock model. Solution: define permanent paddocks, manage subdivisions operationally.

**Non-grazing land uses**
Paddocks used for hay cutting, cropping, or non-grazing purposes have different recovery dynamics. Solution: mark these paddocks appropriately or exclude from rotation.

**Unusual stocking situations**
Very high or very low stocking rates distort the standard recovery assumptions. Solution: adjust rest period thresholds.

Recognizing these limits helps you use the platform appropriately—trusting it where it's strong, compensating where it's weak.`,
    },
  ],
  relatedArticles: [
    '/docs/farm-setup/paddocks',
    '/docs/farm-setup/sections',
    '/docs/core-concepts/overview',
  ],
}
